In [1]:
# Numpyインストール
import numpy

In [2]:
# 1次元配列
a = numpy.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [4]:
# 2次元配列
b = numpy.array([[0, 1, 2], [3, 4, 5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [5]:
# 要素が4つの1次元配列
print("a.shape", a.shape)

# 要素が3つの2次元配列
print("b.shape", b.shape)

a.shape (4,)
b.shape (2, 3)


In [6]:
# 要素数
print("a.size", a.size)
print("b.size", b.size)

a.size 4
b.size 6


In [7]:
# 0から4までの整数を持つ配列を生成
print(numpy.arange(5))

[0 1 2 3 4]


In [9]:
# 1から9までの整数のうち奇数の配列を生成
# → 1から9まで+2ずつ整数取り出す
print(numpy.arange(1, 10, 2))

[1 3 5 7 9]


In [10]:
# 0から5までの整数配列
print("6", numpy.arange(6))
# 0から5までの整数配列を変形（要素数は同じでないといけない）
print("2×3", numpy.arange(6).reshape(2, 3))

6 [0 1 2 3 4 5]
2×3 [[0 1 2]
 [3 4 5]]


In [14]:
# 2.0から3.0までの区間で5つの値を等間隔で生成し配列化
# → 0.25ごと
print(numpy.linspace(2.0, 3.0, num=5))

# 区間の終了を配列に含めないときは endpoint=False
print(numpy.linspace(2.0, 3.0, num=5, endpoint=False))

# 間隔の値も同時に取得したいときは retstep=True
a, step = numpy.linspace(2.0, 3.0, num=5, retstep=True)
print(a)
print(step)

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]
[2.   2.25 2.5  2.75 3.  ]
0.25


In [17]:
# 5つの1を持つ1次元配列
print(numpy.ones(5))

# 3行2列の２次元配列
print(numpy.ones((3, 2)))

[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
# 5つの0を持つ1次元配列
print(numpy.zeros(5))

# 3行2列の2次元配列
print(numpy.zeros((3, 2)))

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [21]:
# 対角要素が1となる2次元配列生成
print(numpy.eye(2))

[[1. 0.]
 [0. 1.]]
