In [1]:
# Numpyインストール
import numpy

In [2]:
a = numpy.arange(1, 5)
print(a)

[1 2 3 4]


In [3]:
# 各要素の y = tan(x) を求める　三角関数
print(numpy.tan(a))

[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [4]:
# 各要素の y = exp(x) を求める　指数関数
print(numpy.exp(a))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [5]:
# 各要素の y = log(x) を求める　対数関数
print(numpy.log(a))

[0.         0.69314718 1.09861229 1.38629436]


# 統計入門

## 分散
データがどれくらいばらついているかを値にしたもの  
求め方は「平均からの差の２乗」の平均  
例：↓のaのテストの結果 [50, 60, 70, 70, 100]で考えると  
`分散 = ( (50-70)^2 + (60-70)^2 + (70-70)^2 + (70-70)^2  + (100-70)^2 ) / 5 = 280（点^2） `  
  
## 標準偏差
分散は数値を2乗しているので単位が合わない  
平均や中央値の単位は点だけど分散の単位は点^2になり指標としては良くない  
他の指標と比較するため単位を合わせる必要があり、分散の正の平方根が標準偏差となる
例：↓のaで考えると  
`標準偏差 = +√280 ≒ 16.73（点）`  
  
### 68%95%ルール
データの確率分布が正規分布の形をしている場合、  
* 平均-1*標準偏差 〜 平均+1*標準偏差 にデータが含まれている確率が68%
* 平均-2*標準偏差 〜 平均+2*標準偏差 にデータが含まれている確率が95%

In [6]:
# aのテストの結果 [50, 60, 70, 70, 100]
a_score = numpy.array([50, 60, 70, 70, 100])
print("総和 ", numpy.sum(a_score))
print("平均 ", numpy.mean(a_score))
print("中央値 ", numpy.median(a_score))
print("分散 ", numpy.var(a_score))
print("標準偏差 ", numpy.std(a_score))
print("最小値 ", numpy.min(a_score))
print("最小値のインデックス ", numpy.argmin(a_score))
print("最大値 ", numpy.max(a_score))
print("最大値のインデックス ", numpy.argmax(a_score))

総和  350
平均  70.0
中央値  70.0
分散  280.0
標準偏差  16.73320053068151
最小値  50
最小値のインデックス  0
最大値  100
最大値のインデックス  4


In [7]:
# bのテストの結果 [69, 70, 70, 70, 71]
b_score = numpy.array([69, 70, 70, 70, 71])
print("総和 ", numpy.sum(b_score))
print("平均 ", numpy.mean(b_score))
print("中央値 ", numpy.median(b_score))
print("分散 ", numpy.var(b_score))
print("標準偏差 ", numpy.std(b_score))
print("最小値 ", numpy.min(b_score))
print("最小値のインデックス ", numpy.argmin(b_score))
print("最大値 ", numpy.max(b_score))
print("最大値のインデックス ", numpy.argmax(b_score))

総和  350
平均  70.0
中央値  70.0
分散  0.4
標準偏差  0.6324555320336759
最小値  69
最小値のインデックス  0
最大値  71
最大値のインデックス  4


In [9]:
b = numpy.arange(6).reshape(2, 3)
print("b=", b)
print("axis=0", b.sum(axis=0))
print("axis=1", b.sum(axis=1))
print("total", b.sum())

b= [[0 1 2]
 [3 4 5]]
axis=0 [3 5 7]
axis=1 [ 3 12]
total 15


In [13]:
b0 = b.sum(axis=0, keepdims=True)
print("axis=0", b0)
print("axis=0 shape", b0.shape) # 次元情報
b1 = b.sum(axis=1, keepdims=True)
print("axis=1", b1)
print("axis=1 shape", b1.shape) # 次元情報

axis=0 [[3 5 7]]
axis=0 shape (1, 3)
axis=1 [[ 3]
 [12]]
axis=1 shape (2, 1)


# ソート関数

In [14]:
a = numpy.array([4, 3, 1, 4, 2])
print(a)

[4 3 1 4 2]


In [15]:
# 配列の要素をソート
print(numpy.sort(a))

[1 2 3 4 4]


In [16]:
# ソート結果をインデックスで取得
print(numpy.argsort(a))

[2 4 1 0 3]


In [17]:
mask = numpy.argsort(a)
print(a[mask])

[1 2 3 4 4]
